# Generated by Django 4.0.6 on 2022-07-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criticas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libre',
            new_name='Libro',
        ),
    ]
