# Generated by Django 4.0.6 on 2022-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticas', '0002_rename_libre_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='El nombre del colaborador', max_length=50)),
                ('apellido', models.CharField(max_length=50, verbose_name='El apellido del colaborador')),
                ('email', models.CharField(max_length=200, verbose_name='El email del colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='El titulo del Editor', max_length=50)),
                ('website', models.CharField(max_length=200, verbose_name='El website el Editor')),
                ('email', models.CharField(max_length=200, verbose_name='El email del Editor')),
            ],
        ),
    ]
