"""
ESTADOS DEL SURFISTA
"""
ESTADO_TUMBADO = 0
ESTADO_REMANDO = 1
ESTADO_NAVEGANDO = 2
ESTADO_NAVEGACION_TERMINADA = 3
ESTADO_CAIDO = 4

DICCIONARIO_ESTADOS_TABLA_SURF = {
    ESTADO_TUMBADO: 'Tumbado',
    ESTADO_REMANDO: 'Remando',
    ESTADO_NAVEGANDO: 'Navegando de pie',
    ESTADO_NAVEGACION_TERMINADA: 'Navegacion terminada',
    ESTADO_CAIDO: 'Caido',
}
